version: '3.4'

services:
  sindacms:
    image: sinda.azurecr.io/sindacmsapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      ConnectionString: server=db,1433;database=sindacmsdb;Uid=sa;Password=P@ssword123;Integrated Security=False
      MigrateDbOnStartup: "true"
      ASPNETCORE_ENVIRONMENT: Production

  db:
    image: mcr.microsoft.com/mssql/server
    hostname: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssword123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
volumes:
  data:
