##
version: '3.4'

services:
  sindacms:
    image: sindaregistry.azurecr.io/sindacmswebapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "Server=tcp:sinda-cms-db-server.database.windows.net,1433;Database=sinda-cms-db;Uid=sa;Password=P@ssword123;Encrypt=true;Connection Timeout=30;"
      - "MigrateDbOnStartup=true"
      - "ASPNETCORE_ENVIRONMENT=Production"

  db:
    image: mcr.microsoft.com/mssql/server
    hostname: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssword123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - net
    restart: always
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
networks:
  net: 
    driver: bridge
volumes:
  data:
