version: '3.4'

services:
  sindacms:
    image: sindatesttwo.azurecr.io/sindacmstesttwoapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - net
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "ConnectionString=server=db,1433;database=sindacmsdb;Uid=sa;Password=P@ssword123;Integrated Security=False"
      - "MigrateDbOnStartup=true"

  db:
    image: mcr.microsoft.com/mssql/server
    hostname: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssword123"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - net
    restart: always
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
networks:
  net: 
    driver: bridge
volumes:
  data:
