apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: "{{ .Values.image.secretData }}"
metadata:
  namespace: "{{ .Values.namespace }}"
  name: "{{ .Values.image.pullSecretName }}"
type: kubernetes.io/dockerconfigjson